### ISSUE TITLE
OKTO2 texture issue

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#184]
The texture allows you to see straight through the part. The gap is just below the OKTO2 label. Not sure if I missed this the first time or if this is a regression.

![image](https://user-images.githubusercontent.com/22890228/51577565-1f7d0180-1e6f-11e9-8b72-ca5f970f139c.png)

**Comment by ChrisAdderley** [comment]
Could have been introduced during rotation but i can't think how.

**Comment by ChrisAdderley** [comment]
Addressed in #221 , confirmed was always there.

**Comment by TykoTek** [comment]
I'm still seeing it in 694b898  

The bug appears unchanged and is visible in VAB and on the launch pad

![image](https://user-images.githubusercontent.com/22890228/51828080-a979ff80-229f-11e9-9fb8-c4de2748e8a8.png)

**Comment by ChrisAdderley** [comment]
![screenshot104](https://user-images.githubusercontent.com/5642064/51846765-16f15480-22cf-11e9-9424-f60f87068a91.png)

I'm not convinced that's not just the behaviour of the cubemap shader at high angles. See how it is blue and not green. Reexported in the latest commit just to be sure.

**Comment by TykoTek** [comment]
In this pic looking through that gap you can see the two internal conduits that extend out the top and bottom of the OKTO2. That doesn't look like a reflection, but rather an opening.

![image](https://user-images.githubusercontent.com/22890228/51848012-ad267a00-22d1-11e9-878d-840f32ecc7c5.png)

**Comment by ChrisAdderley** [comment]
I checked this in the latest builds and i'm not seeing it. Can you have a check again using the latest master?

**Comment by woeller** [comment]
There are still tiny gaps visible.
![screenshot39](https://user-images.githubusercontent.com/35576383/52152099-8079b600-2675-11e9-9514-a51a6654a670.png)
![screenshot37](https://user-images.githubusercontent.com/35576383/52152117-8a031e00-2675-11e9-9c9c-c0fbe824f8f1.png)
![screenshot36](https://user-images.githubusercontent.com/35576383/52152131-8ff8ff00-2675-11e9-8666-c9a0a772b202.png)

**Comment by ChrisAdderley** [comment]
As discussed in discord, this is a shader artifact that we can't do anything about.
