### ISSUE TITLE
RV-105-X RCS Thruster Block - Texture Alignment Issue

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#393]
The outwards facing black circle surround on the 105-X RCS thruster is misaligned to the nozzle structure, see screenshot:

![untitled-1](https://user-images.githubusercontent.com/10106634/52920864-2d586200-3309-11e9-86e5-630f203dedac.png)

**Comment by TykoTek** [comment]
@Poodmund I believe this was fixed last week with https://github.com/PorktoberRevolution/ReStocked/issues/372.

Is this a regression?

**Comment by Poodmund** [comment]
Yes I think so. It still persists on the latest Master build: https://github.com/PorktoberRevolution/ReStocked/commit/22816295a5edb635b647aabcc6f1c492bd92a49f

**Comment by ChrisAdderley** [comment]
I can't reproduce it: 
![screenshot116](https://user-images.githubusercontent.com/5642064/52982183-6fc97f80-3399-11e9-9e2c-64c76d8fe786.png)

**Comment by Poodmund** [comment]
Weird... I had to completely flush my install and download ReStock archive from the repo to resolve this. Anyway, sorry for time wasted.

Resolved as per https://github.com/PorktoberRevolution/ReStocked/issues/372 I guess.

**Comment by ChrisAdderley** [comment]
Unless the repo is directly cloned into GameData or symlinked, copying the folder will leave trailing tgas into the archive which may or may not be loaded instead of the ddses.
