### ISSUE TITLE
Octagonal Strut - Z-Fighting at top/bottom cross strut connections

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#447]
See the video below showing Z-Fighting on the top and bottom of the part at the connection joints between the cross struts: https://youtu.be/_A1GfYX5H3k

**Comment by ChrisAdderley** [comment]
Fixed e93b8ec

**Comment by Poodmund** [comment]
I'm still experiencing the Z-fighting issue, @TykoTek 	can you confirm this also on the latest build?

**Comment by ChrisAdderley** [comment]
Should be cleaned up now with #482 merged

**Comment by Poodmund** [comment]
The issue still persists on the inside/inner-facing joints in the same area. The outside/outer-facing joints are resolved with https://github.com/PorktoberRevolution/ReStocked/pull/482

Close as resolved or leave open for more work as necessary.

**Comment by ChrisAdderley** [comment]
Closing with b245c5f

**Comment by Poodmund** [comment]
Can confirm resolved with https://github.com/PorktoberRevolution/ReStocked/commit/b245c5ffebce6e795707c09c1ca0ead61ce6dc3d
