### ISSUE TITLE
Kerbodyne S3-7200 - orange variant is misplaced

### ISSUE THREAD

**Issue by blowfishpro** [PorktoberRevolution/ReStocked#473]
Yeah...
![image](https://user-images.githubusercontent.com/10545461/53472814-90d74380-3a1d-11e9-9123-5416cc7e73cf.png)

**Comment by ChrisAdderley** [comment]
Honestly given the fact that I reexported every part the other day, I'm surprised there aren't more problems!

**Comment by ChrisAdderley** [comment]
Fixed e227816

**Comment by blowfishpro** [comment]
Yep, fixed

**Comment by germannorwegian** [comment]
i still have this issue, i tried installing the patch but both my X200 tanks and S3 tanks are bugged to hell exactly like the picture shows. Additionally the textures do not work, only a plain white.. No Orange color available
