### ISSUE TITLE
Kerbodyne Engine Cluster Adapter Tank - Gap between thrust plate and lower nodes

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#826]
![Untitled-1](https://user-images.githubusercontent.com/10106634/79907010-cf457400-8410-11ea-8c4f-0b3ba18eff90.png)

The top image shows the central node and the lower image shows the mounting pod nodes. There is a slight gap between the thrust plate and the node positions.

**Comment by ChrisAdderley** [comment]
Fixed in d9bd0b6b59a6cc27d22149a0cb414156cf2fb3c0

**Comment by Poodmund** [comment]
The outer nodes seem to be resolved but the centre node still appears to be too low.

![Untitled-1](https://user-images.githubusercontent.com/10106634/80023287-34629d80-84d5-11ea-94a8-c81e45681412.png)

**Comment by ChrisAdderley** [comment]
6a4d577a181f462de07f446b02fd9fd795f3a38d resolves this and a stack of other issues with this part.

**Comment by Poodmund** [comment]
Resolved with https://github.com/PorktoberRevolution/ReStocked/commit/6a4d577a181f462de07f446b02fd9fd795f3a38d
